### ISSUE TITLE
Implement USE CASE 1

### ISSUE THREAD

**Issue by Apace1996** [gseteamproject/gseproject#11]
**Task:**
A Robot aks a Pallete how much Blocks are on it. The Pallete replies with it's State.
The output of the Pallete is specified in W-007 and W-008.
Learned: Communication between agent should use ontology.

**Comment by kinnder** [comment]
I think that functionality of SourcePalleteReply, RobotRequest, GoalPalleteReply and other classes that contains only text-constants should be implemented using Ontology mechanism;

Ontology mechanism is designed to give agents content for communication

**Comment by Apace1996** [comment]
I close this issue, since we are starting another aproach. We want to do the whole architecture first.
